name: Publish prod branch
on:
        push:
                branches:
                        - prod

jobs:
        build:
                name: Build and publish the web site
                runs-on: ubuntu-latest
                steps:
                        - name: Build Hugo
                          uses: dpisarenko/hugo-action@master
