name: Publish prod branch
on:
        push:
                branches:
                        - prod

jobs:
        build:
                name: Build and publish web site to hosting provider
                runs-on: ubuntu-latest
                steps:
                        - name: Hello world
                          uses: actions/hello-world-javascript-action@v1
                          with:
                                  who-to-greet: Dmitrii
                          id: hello
                        - name: Echo the greeting's time
                          run: echo 'The time was ${{ steps.hello.outputs.time }}.'
                        - name: Build Hugo
                          uses: dpisarenko/hugo-action@master
                        - name: Output the version of Hugo
                          run: hugo version
