name: Publish prod branch
on:
        push:
                branches:
                        - prod

jobs:
        build:
                name: Build and publish web site to hosting provider
                runs-on: ubuntu-latest
                env:
                        working-directory: .
                steps:
                        - name: Build Hugo
                          uses: dpisarenko/hugo-action@master
